"""Modular pricing bandit experiment code (refactor of ``experiment_realistic``)."""

from .config import (
    ALPHA,
    CFG,
    EXP_CFG,
    ALL_ACTIONS_NORM,
    ALL_ACTIONS_REAL,
    ALL_ALGS,
    BanditExperimentConfig,
    COLORS,
    GRAPH_DICT,
    MARKERS,
    MARGIN_VALS,
    N_ACTIONS,
    N_BASKETS,
    N_PRODUCTS,
    NOISE_VAR,
    NOISE_VAR_MARG,
    PROPOSED_JOINT_ALG,
    JOINT_CONT_GP_UCB_ALG,
    ISO_MATERN_GP_UCB_ALG,
    REWARD_SCALE,
    best_independent_product_surrogate,
    effective_gp_noise_variance,
    normalize_joint_reward,
    recommendation_csv_keys,
    unnormalize_joint_reward,
    validate_full_cartesian_x0,
    played_action_csv_keys,
)
from .kernels import KERNEL_L, _matern12_isotropic, _matern12_product
from .rewards import (
    compute_joint_reward,
    compute_marginal_rewards,
    joint_reward_from_sales,
    mean_joint_reward_replicated,
    norm_to_real,
    snap_to_grid,
)
from .agents import (
    BZ_ETC,
    DMSGPUCB,
    DMSX0BPE,
    HGP_UCB_CPP_Wrapper,
    IsotropicMatern12GPUCB,
    KleinbergUCB,
    SPSAPricing,
    UnivariateBaseline,
    li_22_bpe_batch_sizes,
)
from .runs import run_bpe_x0_only_trace, run_one, run_one_single_algorithm, run_one_two_joint
from .parallel import _run_task, _run_task_single
from .main_entry import main, main_single_agent, run_dependency_strength_ablation

__all__ = [
    "ALPHA",
    "CFG",
    "EXP_CFG",
    "ALL_ACTIONS_NORM",
    "ALL_ACTIONS_REAL",
    "ALL_ALGS",
    "BanditExperimentConfig",
    "COLORS",
    "GRAPH_DICT",
    "MARKERS",
    "MARGIN_VALS",
    "N_ACTIONS",
    "N_BASKETS",
    "N_PRODUCTS",
    "NOISE_VAR",
    "NOISE_VAR_MARG",
    "PROPOSED_JOINT_ALG",
    "JOINT_CONT_GP_UCB_ALG",
    "ISO_MATERN_GP_UCB_ALG",
    "REWARD_SCALE",
    "KERNEL_L",
    "best_independent_product_surrogate",
    "effective_gp_noise_variance",
    "normalize_joint_reward",
    "unnormalize_joint_reward",
    "recommendation_csv_keys",
    "validate_full_cartesian_x0",
    "played_action_csv_keys",
    "_matern12_isotropic",
    "_matern12_product",
    "compute_joint_reward",
    "compute_marginal_rewards",
    "joint_reward_from_sales",
    "mean_joint_reward_replicated",
    "norm_to_real",
    "snap_to_grid",
    "BZ_ETC",
    "DMSGPUCB",
    "DMSX0BPE",
    "HGP_UCB_CPP_Wrapper",
    "IsotropicMatern12GPUCB",
    "KleinbergUCB",
    "SPSAPricing",
    "UnivariateBaseline",
    "li_22_bpe_batch_sizes",
    "run_bpe_x0_only_trace",
    "run_one",
    "run_one_single_algorithm",
    "run_one_two_joint",
    "_run_task",
    "_run_task_single",
    "main",
    "main_single_agent",
    "run_dependency_strength_ablation",
]
